### ISSUE TITLE
Ultimos Dias

### ISSUE THREAD

**Issue by rogerio-pereira** [raniellyferreira/economy-api#1]
Há alguma possibilidade de obter a variação do dolar nos ultimos X dias?
tentei mudar a variavel "Numero de resultados" da chamada, para 30
https://economia.awesomeapi.com.br/{MOEDA}/{Numero de resultados}
mas me retornou 20 variações do mesmo dia

**Comment by raniellyferreira** [comment]
Olá Rogério, essa funcionalidade esta sendo implementada. Aviso quando estiver em produção.

**Comment by raniellyferreira** [comment]
Olá!
Segue exemplo de uso

Últimos 30 dias:
`
https://economy.awesomeapi.com.br/xml/list/USD-BRL/30
`

Periodo específico:
`
https://economy.awesomeapi.com.br/xml/list/USD-BRL/?start_date=20160701&end_date=20160731
`
