### ISSUE TITLE
Erro 403 Forbidden

### ISSUE THREAD

**Issue by lucasborgesbr** [raniellyferreira/economy-api#17]
Boa tarde Ranielly,

primeiramente queria agradecer por produzir a API de forma tão bem feita. E disponibilizar para uso.

Uso sua API de Cotação para Dolar turismo no meu sistema, e hoje fui surpreendido pela seguinte mensagem:

**HTTP request failed! HTTP/1.1 403 Forbidden**

porém no meu navegador continua normal. Apenas as requisições vindo do meu Servidor estão sendo barradas. 
Poderia me ajudar ?

**Comment by raniellyferreira** [comment]
Boa tarde Lucas,
obrigado pelo reconhecimento!

isso aconteceu porque ouve uma falha no load balancer que esta nos Estados Unidos, mas já foi normalizado.

Desculpe o imprevisto!

**Comment by lucasborgesbr** [comment]
Muito obrigado Ranielly! Fiquei com medo de ter estourado um numero de requisições ou algo do tipo. Como meu servidor também fica lá pensei que podia ser um problema! 

Testei aqui e realmente voltou tudo ao normal! 

valeu!
