### ISSUE TITLE
API fora do ar

### ISSUE THREAD

**Issue by icaroharry** [raniellyferreira/economy-api#21]
Boa tarde @raniellyferreira! Primeiramente, obrigado por manter essa API :) 

Ela é muito boa para estudar e fazer aplicações didáticas :100: 

Eu estava usando em um projeto e parece que agora ela está fora do ar. Você sabe o que pode está acontecendo?

Obrigado!

**Comment by lucasborgesbr** [comment]
@raniellyferreira também estou com problemas. Aparentemente algum problema com o balanceamento do nginx novamente.

**Comment by lucasborgesbr** [comment]
Amanheceu fora do ar de novo. Algum parecer @raniellyferreira  ?

**Comment by raniellyferreira** [comment]
Olá bom dia! A API esta de volta no ar. Esse foi um erro humano devido a uma manutenção que fizemos essa madrugada mas o mesmo já foi corrigido. Desculpe o imprevisto
