### ISSUE TITLE
ETH desatualizada

### ISSUE THREAD

**Issue by JefersonOC** [raniellyferreira/economy-api#22]
https://economia.awesomeapi.com.br/json/all/ETH-BRL

{
"ETH": {
"code": "ETH",
"codein": "BRL",
"name": "Ethereum",
"high": "1200.21",
"low": "1200.21",
"varBid": "0",
"pctChange": "0",
"bid": "1440.25",
"ask": "16999.75",
"timestamp": "1610415652",
"create_date": "2021-01-11 22:40:52"
}
}

**Comment by raniellyferreira** [comment]
Olá, é normal ETH para REAL ter vários dias de atraso na atualização.

Obrigado por usar a AwesomeAPI
