### ISSUE TITLE
Problema na conversão de Iene para USD,EUR..

### ISSUE THREAD

**Issue by victorsouzaleal** [raniellyferreira/economy-api#23]
Notei um problema com a conversão de Iene que a API está retornando 1 iene como 0.92 USD e não 0,0092 USD
![image](https://user-images.githubusercontent.com/4674786/115145821-efab0d00-a029-11eb-9cbe-02bc7c99d1ef.png)

Esse mesmo problema ocorre com outras moedas em que o valor convertido fica muito baixo

**Comment by raniellyferreira** [comment]
Olá bom dia, nesses cacos o valor é multiplicado por 100, portanto tera que dividi-lo por 100 para ter o valor que quer.
Futuramente vou colocar uma indicação nas moedas que acontecem isso.
Obrigado pelo report
