### ISSUE TITLE
Formatação de retorno do bitcoin e etherium não estão corretos.

### ISSUE THREAD

**Issue by famarc10** [raniellyferreira/economy-api#27]
Boa tarde,
O retorno do valor de bitcoin para BRL esta vindo sem centavos. ex: 331.999, assim tem que ser tratado a parte, pois o sistema não sabe se é 331.999,00mil ou 331,99reais.
O retorno do Eth também esta errado, possívelmente desatualizado.
Caso seja possível podemos tentar ajudar de alguma forma.

Desde já muito obrigado!

**Comment by raniellyferreira** [comment]
Boa tarde,

O correto seria  R$ 331,999.

Para ter o valor que deseja terá que multiplicar por 1000. Ex: 331,99 * 1000

Abraço.
