### ISSUE TITLE
Problemas na compra com os bot

### ISSUE THREAD

**Issue by danielRaibolt123** [raniellyferreira/economy-api#31]
o mercado subjacente sofreu uma grande oscilação desede que você fixou o preço de contrato, o contrato payout mudou a seu favor.

Alguem sabe me explicar como resolver esse problemas com os bots?
Desenvolvi um bot que no momento da compra fica aparecendo essa mensagem e não realiza a compra, volta a analisar e quando compra aparece essa mensagem e não realiza a compra volta a analisar, fica dó nisso o tempo todo
![Captura de Tela (1050)](https://user-images.githubusercontent.com/42899863/167466380-6afd45a1-4408-4964-bb31-b2328ecaff3f.png)

**Comment by raniellyferreira** [comment]
Olá,

A AwesomeAPI fornece informações para visualização, não trabalhamos com bot.
