### ISSUE TITLE
Euro turismo não aparece

### ISSUE THREAD

**Issue by mastria** [raniellyferreira/economy-api#32]
Não consigo cotar a moeda EUR-BRLT, aparece como Dólar Americano/Real Brasileiro Turismo

Consulta: https://economia.awesomeapi.com.br/last/EUR-BRLT

Caso precise de ajuda para correção, estou à disposição.

Abraços

**Comment by raniellyferreira** [comment]
Olá,

Não fornecemos essa informação, apenas USD-BRLT.
