### ISSUE TITLE
Acredito ter encontrado um bug na cotação JPY-USD e JPY-EUR

### ISSUE THREAD

**Issue by PaulloClara** [raniellyferreira/economy-api#35]
O valor esperado em https://economia.awesomeapi.com.br/json/last/JPY-USD é +/- **0,0076**, no entanto estou recebendo +/- **0.76675**, na cotação JPY-BRL isso não acontece, não notei esse problema nas outras cotações.

**Comment by raniellyferreira** [comment]
Boa tarde @PaulloClara!

Esse valor está retornando assim porque está no formato do Iene japonês.

A cotação mais utilizada é essa que é retornado no formato do dólar
https://economia.awesomeapi.com.br/json/last/USD-JPY

1 dólar americano = 131.08 Iene japonês

Apenas divida um pelo outro:

1 / 131.08 = 0.00762892889

Então 1 Iene equivale a 0.00762892889 centavos de dólar.
