### ISSUE TITLE
API retorna undefined no nome das moedas na chamada

### ISSUE THREAD

**Issue by andreescocard** [raniellyferreira/economy-api#38]
Verifiquei que o nome da moeda na resposta do json vem como undefined
Aproveitando, esse endpoint http://economia.awesomeapi.com.br/all, não existe mais?
Grato

**Comment by gabrielbs-dev** [comment]
Estou enfrentando o mesmo problema, no meu caso estou utilizando o endpoint [https://economia.awesomeapi.com.br/last/USD-BRL](https://economia.awesomeapi.com.br/last/USD-BRL)

**Comment by raniellyferreira** [comment]
Foi uma instabilidade em um dos servidores, desculpem o imprevisto.
