### ISSUE TITLE
Fora do AR! 

### ISSUE THREAD

**Issue by hiderlanio** [raniellyferreira/economy-api#41]
![image](https://github.com/raniellyferreira/economy-api/assets/1874031/0eb4da80-ff4f-48ae-8854-66d1a000aec7)

https://economia.awesomeapi.com.br/json/last/USD-BRL/

Api se encontra fora do AR?

**Comment by tonimoreiraa** [comment]
Sim! Conseguiu achar uma alternativa?

**Comment by hiderlanio** [comment]
Achei essa https://console.hgbrasil.com/documentation/finance

Porém dependendo do tanto de requisição que vc precisar é paga.

**Comment by hiderlanio** [comment]
Voltou mas os valores estão desatualizados, vamos aguardar normalizar

**Comment by tonimoreiraa** [comment]
Boa! Obrigado! Pelo que vi, já está no ar novamente
