### ISSUE TITLE
Como introduzo esta API no meu código?

### ISSUE THREAD

**Issue by italoryansouza** [raniellyferreira/economy-api#44]
Olá, estou começando a aprender programação. Estou estudando HTML, CSS e JS e estou criando um site que faz a conversão de valores monetários. Para manter sempre atualizado os valores da cotação das moedas, queria tentar inserir essa API, mas como sou muito iniciante não faço a mínima ideia de como se faz isso. Alguém pode me ajudar?

**Comment by marcelodeus98** [comment]
Olá , bom dia!

Para consumo dessa API com javascript eu utilizei a própria documentação
mesmo como base, e a manipulação do DOM para entregar as informações, vou
te repassar aqui o código como exemplo:

let Converter = async () => {
    try{

        let valueCoin =
parseFloat(document.getElementById("valueId").value) || 1;
        let coinOne =
document.getElementById("selectMoedaOne").value.split(',')[0];
        let coinTwo =
document.getElementById("selectMoedaTwo").value.split(',')[0];
        let elementConvertido = document.getElementById("valueConvert");

        const app_URL = `
https://economia.awesomeapi.com.br/${coinOne}-${coinTwo}/1`;

         const response = await fetch(app_URL);
            if (!response.ok) {
                throw new Error('Erro ao consumir API');
            }

        const data = await response.json();
        const valueConverted = data[0].low * valueCoin;

        const formatter = new Intl.NumberFormat('en-US', {
            style: 'currency',
            currency: coinTwo,
        });

        elementConvertido.innerHTML = `O valor convertido é :
${formatter.format(valueConverted)}`;
    }
    catch(error) {
        console.error('Erro ao conveter moeda:', error);
    }
}


Mas caso tu queira vê por completo, vou te passa o repositório no Github e
o link do site que estou fazendo com o consumo dessa API

GITHUB:
https://github.com/marcelodeus98/Conversor-de-moedas/blob/main/public/js/index.js
SITE: https://conversor-de-moedas.onrender.com/

Em qua., 5 de jun. de 2024 às 13:57, Ítalo Ryan ***@***.***>
escreveu:

**Comment by italoryansouza** [comment]
Muito obrigado! Vou tentar aplicar
