### ISSUE TITLE
Diferença de tempo entre os campos timestamp e create_date

### ISSUE THREAD

**Issue by thnardi** [raniellyferreira/economy-api#46]
Ola, percebi que existe uma diferença de 3 horas entre o campo timestamp e o campo create_date, gostaria de uma explicação desta diferença e o que significam estes campos com mais detalhes. 

Por que tem dois campos? O que significa cada um e sua diferença.

**Comment by raniellyferreira** [comment]
Olá @thnardi, a diferença é porque o timestamp está em UTC e o create_date está em UTC-3 (horário de Brasília), ambos são a hora recebida do provedor.
