### ISSUE TITLE
apanhando pro jq

### ISSUE THREAD

**Issue by CelsoCaldeira** [raniellyferreira/economy-api#5]
não consigo pegar nenhum valor pelo jq, 
curl http://economia.awesomeapi.com.br/USD-BRL/1|jq '.high'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   233    0   233    0     0   1652      0 --:--:-- --:--:-- --:--:--  1652
jq: error (at <stdin>:0): Cannot index array with string "high"

tentei várias outras formas pra disponíveis no manual e no site do jq pra conseguir o valor do dolar mas sempre essa mesma mensagem de erro.

**Comment by raniellyferreira** [comment]
Olá,

O correto seria
```
curl https://economia.awesomeapi.com.br/USD-BRL/1 | jq .[0].high
```
