### ISSUE TITLE
Se possível adicionar moeda chinesa a API

### ISSUE THREAD

**Issue by VinnyLima** [raniellyferreira/economy-api#6]
Caro Ranielly.
 Primeiramente gostaria de parabeniza-lo pela API desenvolvida, superou minhas expectativas.

uma necessidade que tive é ter a informação da moeda chinesa em comparação com o dólar.
 Ex; USD-CNY.

Se possível e claro. desde já agradeço a atenção.

**Comment by raniellyferreira** [comment]
Olá Vinicius. Obrigado pelo reconhecimento, espero que a API esteja sendo útil.

A conversão de moedas estará disponível em breve. Por enquanto você pode ter CNY-BRL que acabei de colocar.
