### ISSUE TITLE
Diferenca de cotacao

### ISSUE THREAD

**Issue by diegoarcega** [raniellyferreira/economy-api#8]
Opa @raniellyferreira 

Sabe dizer o porque apis como https://api.exchangeratesapi.io/latest?base=USD(existem varias outras) retornam 3.99 no valor do dolar para o dia, enquanto que a sua API retorna 4.05 (que acaba sendo o mesmo valor retornado nas apis como google e https://www.investing.com/currencies/usd-brl) ? (o valor utilizado na cotacao eh soh pra usar como exemplo hoje, tanto faz o valor, o importante eh a diferenca)

Sei que essas apis free tem um delay de 1h normalmente, mas mesmo depois de 1h elas mesmo assim congelam esse valor incorreto. 

Estou perguntando porque estou construindo um app free que mostra esses valores das APIs, mas teoricamente esse app eh pra ser usado por qualquer um em qualquer pais, mas vejo que essas APIs free internacionais estao retornando essa cotacao que nao bate com as cotacoes oficiais aqui no BR. 

Thanks, acredito que no fim vou acabar usando a sua API e me focar nas cotacoes daqui.

**Comment by raniellyferreira** [comment]
Olá Diego!

Não tenho como te dar informações mais detalhadas sobre, mas acredito que essa diferença se deve a taxa que cada casa de cambio tem, onde é calculado os valores de uma moeda para outra, com adição de impostos (talvez).

Essa API atualiza a cada 3 minutos.

**Comment by diegoarcega** [comment]
Obrigado  Ranielly. 
Recentemente encontrei essa api https://rapidapi.com/fyhao/api/currency-exchange?endpoint=53aa60c0e4b0596140341c57 mas ainda nao testei, parece que chega um pouco mais perto. 
Vou ver oq descubro.

Obrigado pela resposta e pela API, eh otima e confiavel pra mim.

Abraco
