### ISSUE TITLE
Cotações não atualizando

### ISSUE THREAD

**Issue by Spasmus** [raniellyferreira/economy-api#9]
<create_date>2019-10-20 16:26:59</create_date>

https://economia.awesomeapi.com.br/xml/USD-BRL/1

**Comment by raniellyferreira** [comment]
Bom dia! Obrigador por reportar, já está atualizando novamente.

**Comment by Spasmus** [comment]
https://economia.awesomeapi.com.br/json/USD-BRL/1

voltou a ficar desatualizado, "create_date":"2019-10-25 17:59:58"
